#!/usr/bin/env sh
# a script to get some entities to play with

mkdir -p test/fixtures
# get the first 50 lines of the latest dump
curl -s https://dumps.wikimedia.org/wikidatawiki/entities/latest-all.json.gz |gzip -d |head -n 50 > ./test/fixtures/entities
